// N-400 Civics Practice - All 100 Original USCIS Questions

const allQuestions = [
    { id: 1, text: "What is the supreme law of the land?", answers: ["The Constitution", "the Constitution"], category: "American Government" },
    { id: 2, text: "What does the Constitution do?", answers: ["Sets up the government", "Defines the government", "Protects the basic rights of Americans"], category: "American Government" },
    { id: 3, text: "The idea of self-government is in the first three words of the Constitution. What are these words?", answers: ["We the People"], category: "American Government" },
    { id: 4, text: "What is an amendment?", answers: ["A change to the Constitution", "An addition to the Constitution"], category: "American Government" },
    { id: 5, text: "What do we call the first ten amendments to the Constitution?", answers: ["The Bill of Rights"], category: "American Government" },
    { id: 6, text: "What is one right or freedom from the First Amendment?", answers: ["speech", "religion", "assembly", "press", "petition", "freedom of speech", "freedom of religion", "freedom of assembly", "freedom of the press", "freedom to petition the government"], category: "American Government" },
    { id: 7, text: "How many branches of government are there in the United States?", answers: ["three", "3"], category: "American Government" },
    { id: 8, text: "What are the three branches of government?", answers: ["legislative", "executive", "judicial"], category: "American Government" },
    { id: 9, text: "What is the legislative branch of government?", answers: ["Congress", "Senate and House", "the Senate and House of Representatives"], category: "American Government" },
    { id: 10, text: "Who makes federal laws?", answers: ["Congress", "the Senate and House of Representatives", "the legislative branch"], category: "American Government" },
    { id: 11, text: "What are the two houses of Congress?", answers: ["the Senate and House of Representatives"], category: "American Government" },
    { id: 12, text: "How many United States Senators are there?", answers: ["100", "one hundred"], category: "American Government" },
    { id: 13, text: "What is the executive branch of government?", answers: ["the President", "the President, Cabinet, and agencies"], category: "American Government" },
    { id: 14, text: "Who is in charge of the executive branch?", answers: ["the President"], category: "American Government" },
    { id: 15, text: "Who is the President of the United States?", answers: ["Donald Trump", "Donald J. Trump", "Trump"], category: "American Government" },
    { id: 16, text: "Who is the Vice President?", answers: ["JD Vance", "J.D. Vance", "Vance"], category: "American Government" },
    { id: 17, text: "What is the judicial branch of government?", answers: ["the Supreme Court", "the courts", "the Supreme Court and other federal courts"], category: "American Government" },
    { id: 18, text: "What does the judicial branch do?", answers: ["Reviews laws", "Explains laws", "Resolves disputes between states", "Decides if laws go against the Constitution"], category: "American Government" },
    { id: 19, text: "What is the Supreme Court?", answers: ["the highest court in the United States"], category: "American Government" },
    { id: 20, text: "How many justices are on the Supreme Court?", answers: ["nine", "9"], category: "American Government" },
    { id: 21, text: "Who is the Chief Justice of the United States?", answers: ["John Roberts", "John G. Roberts", "John G. Roberts Jr.", "Roberts"], category: "American Government" },
    { id: 22, text: "What do we call a change to the Constitution?", answers: ["an amendment"], category: "American Government" },
    { id: 23, text: "How many amendments does the Constitution have?", answers: ["27", "twenty-seven"], category: "American Government" },
    { id: 24, text: "How long do we elect the President?", answers: ["four years", "4 years"], category: "American Government" },
    { id: 25, text: "In what month do we vote for President?", answers: ["November"], category: "American Government" },
    { id: 26, text: "What is the name of the President's official home?", answers: ["the White House"], category: "American Government" },
    { id: 27, text: "What is the name of the President's official workplace?", answers: ["the Oval Office"], category: "American Government" },
    { id: 28, text: "What does the President's cabinet do?", answers: ["Advises the President"], category: "American Government" },
    { id: 29, text: "What are two Cabinet-level positions?", answers: ["Secretary of State", "Secretary of Labor", "Attorney General", "Secretary of Agriculture", "Secretary of Defense", "Secretary of Interior", "Secretary of Treasury", "Secretary of Commerce", "Secretary of Education", "Secretary of Health and Human Services"], category: "American Government" },
    { id: 30, text: "What does the Secretary of State do?", answers: ["Advises the President about foreign policy"], category: "American Government" },
    { id: 31, text: "What is one responsibility that is only for United States citizens?", answers: ["serve on a jury", "vote"], category: "Rights and Responsibilities" },
    { id: 32, text: "What are two rights only for United States citizens?", answers: ["vote", "run for federal office"], category: "Rights and Responsibilities" },
    { id: 33, text: "What is one right of everyone living in the United States?", answers: ["freedom of expression", "freedom of speech", "freedom of assembly", "freedom to petition the government", "freedom of religion", "the right to bear arms"], category: "Rights and Responsibilities" },
    { id: 34, text: "What do we show allegiance to when we say the Pledge of Allegiance?", answers: ["the United States", "the flag"], category: "Rights and Responsibilities" },
    { id: 35, text: "What is one promise you make when you become a United States citizen?", answers: ["to obey the laws of the United States", "to serve in the U.S. military if needed", "to serve the country when needed"], category: "Rights and Responsibilities" },
    { id: 36, text: "How old do citizens have to be to vote for President?", answers: ["eighteen", "18"], category: "Rights and Responsibilities" },
    { id: 37, text: "What are two ways that Americans can participate in their democracy?", answers: ["vote", "join a political party", "help with a campaign", "join a civic organization", "petition the government"], category: "Rights and Responsibilities" },
    { id: 38, text: "When must all men register for the Selective Service?", answers: ["at age 18", "between 18 and 26"], category: "Rights and Responsibilities" },
    { id: 39, text: "What is one reason colonists came to America?", answers: ["freedom", "political liberty", "religious freedom", "economic opportunity", "escape persecution"], category: "American History" },
    { id: 40, text: "Who lived in America before the Europeans arrived?", answers: ["American Indians", "Native Americans"], category: "American History" },
    { id: 41, text: "What group of people was taken to America and sold as slaves?", answers: ["Africans", "people from Africa"], category: "American History" },
    { id: 42, text: "Why did the colonists fight the British?", answers: ["because of high taxes", "because the British army stayed in their homes", "because they did not have self-government"], category: "American History" },
    { id: 43, text: "Who wrote the Declaration of Independence?", answers: ["Thomas Jefferson"], category: "American History" },
    { id: 44, text: "When was the Declaration of Independence adopted?", answers: ["July 4, 1776"], category: "American History" },
    { id: 45, text: "What is the main idea of the Declaration of Independence?", answers: ["that all men are created equal", "people have natural rights"], category: "American History" },
    { id: 46, text: "What did the Declaration of Independence do?", answers: ["announced our independence from Great Britain", "declared that America was independent"], category: "American History" },
    { id: 47, text: "When was the Constitution written?", answers: ["1787"], category: "American History" },
    { id: 48, text: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", answers: ["James Madison", "Alexander Hamilton", "John Jay"], category: "American History" },
    { id: 49, text: "What is one thing Benjamin Franklin is famous for?", answers: ["U.S. diplomat", "oldest delegate to the Constitutional Convention", "first Postmaster General", "writer of Poor Richard's Almanac"], category: "American History" },
    { id: 50, text: "Who is called the \"Father of Our Country\"?", answers: ["George Washington"], category: "American History" },
    { id: 51, text: "Who was the first President?", answers: ["George Washington"], category: "American History" },
    { id: 52, text: "What territory did the United States buy from France in 1803?", answers: ["Louisiana", "the Louisiana Territory"], category: "American History" },
    { id: 53, text: "Name one war fought by the United States in the 1800s.", answers: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"], category: "American History" },
    { id: 54, text: "What did the Emancipation Proclamation do?", answers: ["freed the slaves", "freed slaves in the Confederate states"], category: "American History" },
    { id: 55, text: "What did Susan B. Anthony do?", answers: ["fought for women's rights"], category: "American History" },
    { id: 56, text: "Name one American Indian tribe in the United States.", answers: ["Cherokee", "Navajo", "Sioux", "Chippewa", "Apache", "Blackfeet", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Choctaw", "Seminole"], category: "American History" },
    { id: 57, text: "What was the main concern of the Anti-Federalists?", answers: ["states' rights", "too much federal power"], category: "American History" },
    { id: 58, text: "Which President is on the one dollar bill?", answers: ["George Washington"], category: "American History" },
    { id: 59, text: "Which President is on the five dollar bill?", answers: ["Abraham Lincoln"], category: "American History" },
    { id: 60, text: "Which President is on the ten dollar bill?", answers: ["Alexander Hamilton"], category: "American History" },
    { id: 61, text: "What year was the Constitution written?", answers: ["1787"], category: "American Government" },
    { id: 62, text: "What are the first three words of the Constitution?", answers: ["We the People"], category: "American Government" },
    { id: 63, text: "How many senators does each state have?", answers: ["two", "2"], category: "American Government" },
    { id: 64, text: "How long is a term for a U.S. Senator?", answers: ["six years", "6 years"], category: "American Government" },
    { id: 65, text: "How many times may a Senator be re-elected?", answers: ["no limit"], category: "American Government" },
    { id: 66, text: "How many Representatives are there in Congress?", answers: ["435", "four hundred thirty five"], category: "American Government" },
    { id: 67, text: "How long is a term for a U.S. Representative?", answers: ["two years", "2 years"], category: "American Government" },
    { id: 68, text: "Name your U.S. Representative.", answers: ["answers vary by location"], category: "American Government" },
    { id: 69, text: "Who does a U.S. Senator represent?", answers: ["all people of the state"], category: "American Government" },
    { id: 70, text: "Why do some states have more Representatives than other states?", answers: ["because of population", "because they have more people"], category: "American Government" },
    { id: 71, text: "We elect a U.S. Representative for how long?", answers: ["two years", "2 years"], category: "American Government" },
    { id: 72, text: "Why do we have three branches of government?", answers: ["so that no one branch becomes too powerful", "checks and balances"], category: "American Government" },
    { id: 73, text: "Name one of the two longest rivers in the United States.", answers: ["Missouri River", "Mississippi River"], category: "Geography" },
    { id: 74, text: "What is the capital of Texas?", answers: ["Austin", "Austin, Texas", "Austin, TX"], category: "Geography" },
    { id: 75, text: "What is the capital of the United States?", answers: ["Washington, D.C.", "Washington DC"], category: "Geography" },
    { id: 76, text: "Why does the flag have 13 stripes?", answers: ["because there were 13 original colonies"], category: "American Symbols" },
    { id: 77, text: "Why does the flag have 50 stars?", answers: ["because there are 50 states"], category: "American Symbols" },
    { id: 78, text: "What is the name of the national anthem?", answers: ["The Star-Spangled Banner"], category: "American Symbols" },
    { id: 79, text: "What holiday was celebrated for the first time by American colonists?", answers: ["Thanksgiving"], category: "American Symbols" },
    { id: 80, text: "Name one national U.S. holiday.", answers: ["New Year's Day", "Independence Day", "Thanksgiving", "Christmas"], category: "American Symbols" },
    { id: 81, text: "When is the last day you can send in federal income tax forms?", answers: ["April 15"], category: "Civics" },
    { id: 82, text: "When must you register to vote?", answers: ["differs by state", "before election day"], category: "Civics" },
    { id: 83, text: "What are the two major political parties in the United States?", answers: ["Democratic", "Republican"], category: "Civics" },
    { id: 84, text: "What is the political party of the President now?", answers: ["Republican"], category: "Civics" },
    { id: 85, text: "What is the name of the Speaker of the House of Representatives?", answers: ["Mike Johnson", "Johnson"], category: "American Government" },
    { id: 86, text: "There are four amendments to the Constitution about who can vote. Describe one of them.", answers: ["citizens 18 or older can vote", "you don't have to pay to vote", "any citizen can vote"], category: "Rights and Responsibilities" },
    { id: 87, text: "What is one reason why the government limits the power of the President?", answers: ["to protect democracy", "checks and balances", "separation of powers"], category: "American Government" },
    { id: 88, text: "What is the purpose of the United Nations?", answers: ["for countries to discuss and try to resolve world problems"], category: "Civics" },
    { id: 89, text: "Name one purpose of state government.", answers: ["protect people", "make state laws", "enforce state laws"], category: "American Government" },
    { id: 90, text: "Name one purpose of local government.", answers: ["protect people", "make local laws", "enforce local laws"], category: "American Government" },
    { id: 91, text: "Who signs bills to become laws?", answers: ["the President"], category: "American Government" },
    { id: 92, text: "What does the President's veto power allow him to do?", answers: ["refuse to sign a bill", "prevent a bill from becoming law"], category: "American Government" },
    { id: 93, text: "What is a treaty?", answers: ["an agreement between countries"], category: "American Government" },
    { id: 94, text: "What is the highest court in the United States?", answers: ["the Supreme Court"], category: "American Government" },
    { id: 95, text: "How many continents are there?", answers: ["seven", "7"], category: "Geography" },
    { id: 96, text: "How many oceans are there?", answers: ["five", "4"], category: "Geography" },
    { id: 97, text: "What is the largest state in the United States?", answers: ["Alaska"], category: "Geography" },
    { id: 98, text: "What is the smallest state in the United States?", answers: ["Rhode Island"], category: "Geography" },
    { id: 99, text: "Name the three colors of the flag.", answers: ["red", "white", "blue"], category: "American Symbols" },
    { id: 100, text: "What is the form called to apply to become a United States citizen?", answers: ["N-400", "Application for Naturalization"], category: "Civics" },

    // ===== TEXAS-SPECIFIC CIVICS QUESTIONS (Added for applicants in Texas) =====
    { id: 101, text: "Name one of the two United States Senators from Texas.", answers: ["Ted Cruz", "John Cornyn", "Cruz", "Cornyn"], category: "Texas Government" },
    { id: 102, text: "Who is the United States Representative for Texas's 31st Congressional District (Georgetown/Williamson County area)?", answers: ["John Carter", "Carter"], category: "Texas Government" },
    { id: 103, text: "What is the capital of Texas?", answers: ["Austin"], category: "Texas Geography" },
    { id: 104, text: "In what year did Texas become a state?", answers: ["1845"], category: "Texas History" },
    { id: 105, text: "What river is Texas's most well-known natural border?", answers: ["Rio Grande"], category: "Texas Geography" },
];
